DROP TABLE IF EXISTS incidents;
CREATE TABLE incidents (
  incidentDay text,
  school text,
  city text,
  state text,
  reliabilityScore int,
  killedIncludingShooter int,
  wounded int,
  totalInjuredorKilled int,
  victimsGender text,
  victimsRace text,
  victimsEthnicity text,
  targetedSpecificVictim text,
  bullied text,
  domesticViolence text,
  prePlannedAttack text,
  summary text,
  category text,
  schoolType text,
  narrative text,
  timeofIncident text,
  duringSchoolDay text,
  duringSportEvent text,
  duringSchoolEvent text,
  location text,
  numberofShotsFired int,
  weaponType text,
  shooterName text,
  shooterAge int,
  shooterGender text,
  shooterAffiliationtoSchool text,
  hostagesTaken text

);
